### ISSUE TITLE
Found Inf or NaN global norm. : Tensor had NaN values [Op:CheckNumerics]

### ISSUE THREAD

**Issue by huan** [zixia/concise-chit-chat#1]
It might be related to the vanishing/exploding gradient.

https://github.com/zixia/concise-chit-chat/blob/f837d352fbc70dbe83f08fd7876b0cac7f4ec65e/src/train.py#L143-L154

```
$ make train
PYTHONPATH=src/ python3 src/train.py
got glove embedding for 400000 words
0 entries completed
5000 entries completed
10000 entries completed
2018-10-09 02:34:15.379502: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Start training ...
Epoch 1/10
 42/804 [>.............................] - ETA: 4:45 - loss: 1.7969 - acc: 0.0516Traceback (most recent call last):
  File "src/train.py", line 164, in <module>
    batch_size=16,
  File "/home/zixia/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1579, in fit
    validation_steps=validation_steps)
  File "/home/zixia/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_eager.py", line 698, in fit_loop
    batch_size=batch_size)
  File "/home/zixia/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_eager.py", line 250, in iterator_fit_loop
    model, x, y, sample_weights=sample_weights, training=True)
  File "/home/zixia/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_eager.py", line 516, in _process_single_batch
    model._collected_trainable_weights))
  File "/home/zixia/.local/lib/python3.6/site-packages/tensorflow/python/keras/optimizers.py", line 706, in apply_gradients
    self.optimizer.apply_gradients(grads, global_step=self.iterations)
  File "/home/zixia/.local/lib/python3.6/site-packages/tensorflow/contrib/estimator/python/estimator/extenders.py", line 325, in apply_gradients
    grads_and_vars = self._transform_grads_fn(grads_and_vars)
  File "/home/zixia/.local/lib/python3.6/site-packages/tensorflow/contrib/estimator/python/estimator/extenders.py", line 134, in clip_grads
    gradients = clip_ops.clip_by_global_norm(gradients, clip_norm)[0]
  File "/home/zixia/.local/lib/python3.6/site-packages/tensorflow/python/ops/clip_ops.py", line 259, in clip_by_global_norm
    "Found Inf or NaN global norm.")
  File "/home/zixia/.local/lib/python3.6/site-packages/tensorflow/python/ops/numerics.py", line 45, in verify_tensor_all_finite
    verify_input = array_ops.check_numerics(t, message=msg)
  File "/home/zixia/.local/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 841, in check_numerics
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 2, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Found Inf or NaN global norm. : Tensor had NaN values [Op:CheckNumerics]
Makefile:66: recipe for target 'train' failed
make: *** [train] Error 1
```

**Comment by huan** [comment]
Todo: try to use `GradientTape` to calculate by hand

**Comment by Rorschaaaach** [comment]
请问具体怎么解决这个问题呢，我改变学习率之后这个情况有所变化，但是在迭代次数增加后还是会出现这个问题，谢谢！

**Comment by manuelmolano** [comment]
Hello, any news on this? I am using BasicRNNCell with ReLU activation and I keep getting this message after a few iterations.
thanks!
m.
