### ISSUE TITLE
Deal with bad train

### ISSUE THREAD

**Issue by qhduan** [zixia/concise-chit-chat#3]
1. Fix texts_to_padded_sequences, make it could do 'pre' padding.
2. Do pre padding in encoder and post padding in decoder.

There's why:

LSTM has only one direction, if you do some sequences like: [1, 2, 3, 4, 0, 0, 0, 0], 0 is the padding, this thing make LSTM lost a lot of information( or hardly keep information ).

That's why keras do 'pre' padding in default, that is: [0, 0, 0, 0, 1, 2, 3, 4]

No, bi-lstm will not solve this problem, it could solve half of problem, because you make one direction offline too. The ultra answer is use some thing like:

torch.nn.utils.rnn.pack_padded_sequence

and

torch.nn.utils.rnn.pad_packed_sequence

in pytorch, (Sorry I forgot what the same methods in TF)

```python
    def texts_to_padded_sequences(
            self,
            text_list: List[List[str]],
            padding='post' # or pre
    ) -> tf.Tensor:
        '''doc'''
        sequence_list = self.tokenizer.texts_to_sequences(text_list)
        padded_sequences = tf.keras.preprocessing.sequence.pad_sequences(
            sequence_list,
            maxlen=MAX_LEN,
            padding=padding,
            truncating='post',
        )

        return padded_sequences

```

```python
queries_sequences = vocabulary.texts_to_padded_sequences(queries, padding='pre')
        responses_sequences = vocabulary.texts_to_padded_sequences(responses)
```

I decreased train set to only 30, and there's result, not very good, but a good start

```sh
PYTHONPATH=. python3 bin/train.py
DataLoader downloading dataset from: https://github.com/zixia/concise-chit-chat/releases/download/v0.0.1/dataset.txt.gz
DataLoader loading dataset from: /home/qhduan/.keras/datasets/concise-chit-chat-dataset.txt.gz
2018-11-19 20:40:30.452493: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Dataset size: 30, Vocabulary size: 146
checkpoint restored.
------- step 0 , loss 26.717678 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> why not ? 
> , , , , but , but , but yeah yeah yeah t thousand  never .  never .
>>>>>>>>>>>>>>>>>>>>>>>>>>>> get out ! 
> , , , , , but , but , but yeah yeah yeah t thousand  never .  never
>>>>>>>>>>>>>>>>>>>>>>>>>>>> i was kidding . people actually live there ? 
> . , , , but , but , but yeah yeah yeah t  never .  never . then
checkpoint saved.
------- step 10 , loss 26.015606 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> no . 
>                    
>>>>>>>>>>>>>>>>>>>>>>>>>>>> yeah . 
>                    
>>>>>>>>>>>>>>>>>>>>>>>>>>>> you re asking me out . 
>                    
------- step 20 , loss 33.995461 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> get out ! 
>                    
>>>>>>>>>>>>>>>>>>>>>>>>>>>> exactly my point 
>                    
>>>>>>>>>>>>>>>>>>>>>>>>>>>> well , yes , compared to your other choices of expression this 
>                    
------- step 30 , loss 37.556053 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> i know . 
> ! .                  
>>>>>>>>>>>>>>>>>>>>>>>>>>>> did you change your hair ? 
> ! .                  
>>>>>>>>>>>>>>>>>>>>>>>>>>>> i know . 
> ! .                  
------- step 40 , loss 39.510574 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> okay . 
> i i .                 
>>>>>>>>>>>>>>>>>>>>>>>>>>>> i was kidding . people actually live there ? 
> i .                  
>>>>>>>>>>>>>>>>>>>>>>>>>>>> well , yes , compared to your other choices of expression this 
> i .                  
------- step 50 , loss 33.712532 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> but she doesn t want to date . 
> i .                  
>>>>>>>>>>>>>>>>>>>>>>>>>>>> i was kidding . people actually live there ? 
> i .                  
>>>>>>>>>>>>>>>>>>>>>>>>>>>> so they tell me ... 
> i .                  
------- step 60 , loss 28.027050 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> but she doesn t want to date . 
> i i .                 
>>>>>>>>>>>>>>>>>>>>>>>>>>>> how many people go here ? 
> i i .                 
>>>>>>>>>>>>>>>>>>>>>>>>>>>> exactly my point 
> i i .                 
------- step 70 , loss 24.957691 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> no . 
> i i .                 
>>>>>>>>>>>>>>>>>>>>>>>>>>>> okay . 
> i i .                 
>>>>>>>>>>>>>>>>>>>>>>>>>>>> well , yes , compared to your other choices of expression this 
> i .                  
------- step 80 , loss 29.339167 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> yeah . 
> i i .                 
>>>>>>>>>>>>>>>>>>>>>>>>>>>> you re not helping . 
> i i .                 
>>>>>>>>>>>>>>>>>>>>>>>>>>>> he always look so 
> i i .                 
------- step 90 , loss 23.483274 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> just a little . 
> i you .                 
>>>>>>>>>>>>>>>>>>>>>>>>>>>> i was kidding . people actually live there ? 
> i .                  
>>>>>>>>>>>>>>>>>>>>>>>>>>>> yeah . 
> i you .                 
------- step 100 , loss 20.607203 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> north , actually . how d you ? 
> no .                  
>>>>>>>>>>>>>>>>>>>>>>>>>>>> why not ? 
> no i .                 
>>>>>>>>>>>>>>>>>>>>>>>>>>>> what if she never starts dating ? 
> no .                  
checkpoint saved.
------- step 110 , loss 26.344757 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> north , actually . how d you ? 
> no , .                 
>>>>>>>>>>>>>>>>>>>>>>>>>>>> forget it . 
> no , , , it it              
>>>>>>>>>>>>>>>>>>>>>>>>>>>> where ve you been ? 
> no .                  
------- step 120 , loss 22.881607 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> get out ! 
> i no .                 
>>>>>>>>>>>>>>>>>>>>>>>>>>>> why not ? 
> i no , , it it              
>>>>>>>>>>>>>>>>>>>>>>>>>>>> north , actually . how d you ? 
> i .                  
------- step 130 , loss 18.337414 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> you know french ? 
> i you .                 
>>>>>>>>>>>>>>>>>>>>>>>>>>>> no ! 
> i no , , it it              
>>>>>>>>>>>>>>>>>>>>>>>>>>>> you the new guy ? 
> i you .                 
------- step 140 , loss 16.429169 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> then neither will you . 
> i no , it it               
>>>>>>>>>>>>>>>>>>>>>>>>>>>> i know . 
> i no , , it it s s t t have         
>>>>>>>>>>>>>>>>>>>>>>>>>>>> but she doesn t want to date . 
> i no , , , , , it .           
------- step 150 , loss 15.988334 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> then neither will you . 
> i you .                 
>>>>>>>>>>>>>>>>>>>>>>>>>>>> well , yes , compared to your other choices of expression this 
> i .                  
>>>>>>>>>>>>>>>>>>>>>>>>>>>> but she doesn t want to date . 
> i .                  
------- step 160 , loss 15.754500 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> thirty two . 
> i no , , it it s s s t have         
>>>>>>>>>>>>>>>>>>>>>>>>>>>> did you change your hair ? 
> i .                  
>>>>>>>>>>>>>>>>>>>>>>>>>>>> why not ? 
> i no , , it it s s s t have         
------- step 170 , loss 15.589033 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> no ! 
> no , , it s s s have            
>>>>>>>>>>>>>>>>>>>>>>>>>>>> you know french ? 
> no , it s s s s a have           
>>>>>>>>>>>>>>>>>>>>>>>>>>>> exactly my point 
> no , , it s s s a have           
------- step 180 , loss 17.725128 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> just a little . 
> no , , it s s a have            
>>>>>>>>>>>>>>>>>>>>>>>>>>>> why not ? 
> no , , it s s my fault have           
>>>>>>>>>>>>>>>>>>>>>>>>>>>> forget it . 
> no , , it s s my fault have           
------- step 190 , loss 15.071338 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> that i m used to . 
> i decided .                 
>>>>>>>>>>>>>>>>>>>>>>>>>>>> how many people were in your old school ? 
> you .                  
>>>>>>>>>>>>>>>>>>>>>>>>>>>> i was kidding . people actually live there ? 
> you .                  
------- step 200 , loss 12.004116 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> i was kidding . people actually live there ? 
> you .                  
>>>>>>>>>>>>>>>>>>>>>>>>>>>> you the new guy ? 
> i could .                 
>>>>>>>>>>>>>>>>>>>>>>>>>>>> but she doesn t want to date . 
> i still maintain that he he himself in the balls .         
checkpoint saved.
------- step 210 , loss 12.521299 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> get out ! 
> how many people go here ?              
>>>>>>>>>>>>>>>>>>>>>>>>>>>> how many people go here ? 
> i decided .                 
>>>>>>>>>>>>>>>>>>>>>>>>>>>> you the new guy ? 
> i could .                 
------- step 220 , loss 13.192391 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> exactly my point 
> how many people go here ?              
>>>>>>>>>>>>>>>>>>>>>>>>>>>> you know french ? 
> i could start with your haircut , but it doesn t matter        
>>>>>>>>>>>>>>>>>>>>>>>>>>>> he always look so 
> i still maintain that he kicked himself the balls .          
------- step 230 , loss 9.193684 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> now don t get upset . 
> no !                  
>>>>>>>>>>>>>>>>>>>>>>>>>>>> i know . 
> i could start with your haircut , but it doesn t matter        
>>>>>>>>>>>>>>>>>>>>>>>>>>>> thirty two . 
> i could start with your haircut , but it doesn t matter        
------- step 240 , loss 11.727905 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> no ! 
> i could start your your haircut , but it doesn t matter        
>>>>>>>>>>>>>>>>>>>>>>>>>>>> where ve you been ? 
> i we decided .                
>>>>>>>>>>>>>>>>>>>>>>>>>>>> well , yes , compared to your other choices of expression this 
> i still maintain that he kicked himself in the balls .         
------- step 250 , loss 8.272629 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> thirty two . 
> i could start with your haircut , but it doesn t matter        
>>>>>>>>>>>>>>>>>>>>>>>>>>>> you the new guy ? 
> i thought we decided you were going to school .          
>>>>>>>>>>>>>>>>>>>>>>>>>>>> you re asking me out . 
> i still kidding .                
------- step 260 , loss 8.249215 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> did you change your hair ? 
> i still maintain that he kicked himself in the balls .         
>>>>>>>>>>>>>>>>>>>>>>>>>>>> he always look so 
> i still maintain that he kicked himself in the balls .         
>>>>>>>>>>>>>>>>>>>>>>>>>>>> you re not helping . 
> i we make this quick ?              
------- step 270 , loss 7.322756 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> yeah . 
> no , no , it s my fault we didn t have        
>>>>>>>>>>>>>>>>>>>>>>>>>>>> you re not helping . 
> can we make this quick ?              
>>>>>>>>>>>>>>>>>>>>>>>>>>>> how many people were in your old school ? 
> i still maintain that he kicked himself in the balls .         
------- step 280 , loss 6.287617 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> why not ? 
> i could start with your haircut , but it doesn t matter        
>>>>>>>>>>>>>>>>>>>>>>>>>>>> yeah . 
> no , no , it s my fault we didn t have        
>>>>>>>>>>>>>>>>>>>>>>>>>>>> now don t get upset . 
> no !                  
------- step 290 , loss 7.910484 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> he always look so 
> i still maintain that he kicked himself in the balls .         
>>>>>>>>>>>>>>>>>>>>>>>>>>>> then neither will you . 
> but it s not fair she s a mutant , daddy !        
>>>>>>>>>>>>>>>>>>>>>>>>>>>> north , actually . how d you ? 
> i was kidding . people actually live there ?           
------- step 300 , loss 7.372733 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> but she doesn t want to date . 
> exactly my point                 
>>>>>>>>>>>>>>>>>>>>>>>>>>>> you know french ? 
> i thought we decided you were going to school here .         
>>>>>>>>>>>>>>>>>>>>>>>>>>>> yeah . 
> how many people were in your old school ?           
checkpoint saved.
------- step 310 , loss 5.120145 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> then neither will you . 
> but it s not fair she s a mutant , daddy !        
>>>>>>>>>>>>>>>>>>>>>>>>>>>> where ve you been ? 
> nowhere ... hi , daddy .              
>>>>>>>>>>>>>>>>>>>>>>>>>>>> how many people go here ? 
> couple thousand . most of them evil             
------- step 320 , loss 5.013429 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> so they tell me ... 
> c mon . i m supposed to give you the tour .        
>>>>>>>>>>>>>>>>>>>>>>>>>>>> exactly my point 
> how many people go here ?              
>>>>>>>>>>>>>>>>>>>>>>>>>>>> that i m used to . 
> yeah , but these guys have never seen a horse .         
------- step 330 , loss 4.245070 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> you re not helping . 
> can we make this quick ?              
>>>>>>>>>>>>>>>>>>>>>>>>>>>> well , yes , compared to your other choices of expression this 
> i still maintain that he kicked himself in the balls .         
>>>>>>>>>>>>>>>>>>>>>>>>>>>> exactly my point 
> jesus !                  
------- step 340 , loss 3.674403 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> then neither will you . 
> but it s not fair she s a mutant , daddy !        
>>>>>>>>>>>>>>>>>>>>>>>>>>>> why not ? 
> i could start with your haircut , but it doesn t matter        
>>>>>>>>>>>>>>>>>>>>>>>>>>>> i was kidding . people actually live there ? 
> yeah .                  
------- step 350 , loss 3.594064 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> what if she never starts dating ? 
> then neither will you .               
>>>>>>>>>>>>>>>>>>>>>>>>>>>> no ! 
> you might wanna think about it              
>>>>>>>>>>>>>>>>>>>>>>>>>>>> i was kidding . people actually live there ? 
> yeah .                  
------- step 360 , loss 3.051002 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> you re not helping . 
> can we make this quick ?              
>>>>>>>>>>>>>>>>>>>>>>>>>>>> where ve you been ? 
> nowhere ... hi , daddy .              
>>>>>>>>>>>>>>>>>>>>>>>>>>>> exactly my point 
> you re asking me out .              
------- step 370 , loss 3.758334 -------
>>>>>>>>>>>>>>>>>>>>>>>>>>>> i know . 
> i thought we decided you were going to school here .         
>>>>>>>>>>>>>>>>>>>>>>>>>>>> but she doesn t want to date . 
> exactly my point                 
>>>>>>>>>>>>>>>>>>>>>>>>>>>> i was kidding . people actually live there ? 
> yeah .                  
^CTraceback (most recent call last):
  File "/home/qhduan/Work/concise-chit-chat/env/lib/python3.6/site-packages/tensorflow/python/eager/backprop.py", line 602, in _ones
    def _ones(shape, dtype):
KeyboardInterrupt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bin/train.py", line 216, in <module>
    
  File "bin/train.py", line 169, in main
    def main() -> int:
  File "bin/train.py", line 119, in train
    print(responses_sequences[0])
  File "bin/train.py", line 65, in grad
    gradients = tape.gradient(loss_value, model.variables)
  File "/home/qhduan/Work/concise-chit-chat/env/lib/python3.6/site-packages/tensorflow/python/eager/backprop.py", line 901, in gradient
    output_gradients=output_gradients)
  File "/home/qhduan/Work/concise-chit-chat/env/lib/python3.6/site-packages/tensorflow/python/eager/imperative_grad.py", line 64, in imperative_grad
    output_gradients)
  File "/home/qhduan/Work/concise-chit-chat/env/lib/python3.6/site-packages/tensorflow/python/eager/backprop.py", line 112, in _gradient_function
    mock_op = _MockOp(attr_tuple, inputs, outputs, op_name)
SystemError: <class 'tensorflow.python.eager.backprop._MockOp'> returned a result with an error set
Makefile:62: recipe for target 'train' failed
make: *** [train] Interrupt


```

**Comment by huan** [comment]
Awesome, that's the problem!

@824zzy and I noticed that the `context` that the `encoder` output is very similar and feels there's some problem with it, but we did not find that the sequence padding order matters the LSTM encoder.

Thank you very much for the help!

**Comment by huan** [comment]
Today I had another experiment using the old `padding=post` using a train set with size 256.

It seems with the `post` padding, it can still work very well like `pre`.

So there's might be other problem here...

**Comment by qhduan** [comment]
Remove GO and DONE from input sentence have a little help to train

**Comment by qhduan** [comment]
I have something try yesterday, no update

I think with small size dataset could be fitted means basically OK.

According the result, I think the model learned how to cheat, like every sentences have DONE sign and '.' or 'I', so it have learnt too fast with these.

There're some tricks I don't try, too busy these days, like set different learning rate to encoder and decoder

**Comment by huan** [comment]
Thanks for keep trying it!

I noticed that at the tutorial from pyTorch, they use a 5X learning rate for the decoder then encoder.

Will keep playing with it...
